### PR TITLE
replace czlib with go-libdeflate

### PR DESCRIPTION
**Pull request by paulmach**
merged https://github.com/paulmach/osm/pull/50 into here so I could fix the errors.  See that PR for more details.

I was unable to run this locally, so sort of linker issues. Will need to debug.

### CODE REVIEW

**Comment by oflebbe** [comment]
I can reproduce the issue and asking myself what is going on, since I am pretty sure it worked flawless on my mac before.
I am a bit short of time the now, will update the PR when I am back.

**Comment by OlafFlebbeBosch** [comment]
Ah ok, the linking issue is not present on intel macos.

**Comment by oflebbe** [comment]
Ok will retract. There are serious issues with go-deflate: https://github.com/4kills/go-libdeflate/tree/master/v2/native/libs does not contain darwin/arm64 , the libs included can not to be compatible to both musl and glibc based systems. IMO a an questionale approach to bundle binary libs.

**Comment by paulmach** [comment]
I will close. If this comes up we could allow people to provide their own implementations via some sort of `Decode(out, in []byte) error`.  But I personally don't think decode performance is a bottleneck is "real" usage.

**Pull request closed without merging**
