### PR TITLE
osmpbf: support "sparse" dense nodes

### PR DESCRIPTION
**Pull request by paulmach**
Not all pbf files will have all the timestamp, username, changeset, etc. data so we should be okay with skipping that. No need to stop and return an error.

https://github.com/paulmach/osm/issues/31

@dmholtz does this work on your file?

### CODE REVIEW

**Comment by dmholtz** [comment]
@paulmach Thank you very much for the quick response.

In the diff, I've see that you have introduced nil pointers in case parts of the node information is missing. Unfortunately, the error propagates into your protoscan module, where another runtime error is thrown. Once `scanner.skipNodes = true` is set, no error is thrown.

Btw, I'm negotiation with my university to provide you the custom OSM file asap.

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1009635f0]

goroutine 41 [running]:
github.com/paulmach/protoscan.(*Iterator).HasNext(...)
        /Users/david/go/pkg/mod/github.com/paulmach/protoscan@v0.2.1/iterator.go:39
github.com/paulmach/osm/osmpbf.(*dataDecoder).extractDenseNodes(0x14000120410)
        /Users/david/repos/osm/osmpbf/decode_data.go:347 +0x130
github.com/paulmach/osm/osmpbf.(*dataDecoder).scanDenseNodes(0x14000120410, {0x140023da46c?, 0x14000100000?, 0x14000125970?})
        /Users/david/repos/osm/osmpbf/decode_data.go:334 +0x3b8
github.com/paulmach/osm/osmpbf.(*dataDecoder).scanPrimitiveGroup(0x14000120410, {0x140023da468?, 0x2461?, 0x156d1?})
        /Users/david/repos/osm/osmpbf/decode_data.go:162 +0x94
github.com/paulmach/osm/osmpbf.(*dataDecoder).scanPrimitiveBlock(0x14000120410, {0x140023d8000?, 0x140000762a0?, 0x0?})
        /Users/david/repos/osm/osmpbf/decode_data.go:135 +0x3a0
github.com/paulmach/osm/osmpbf.(*dataDecoder).Decode(0x14000120410, 0x0?)
        /Users/david/repos/osm/osmpbf/decode_data.go:58 +0xe8
github.com/paulmach/osm/osmpbf.(*decoder).Start.func1()
        /Users/david/repos/osm/osmpbf/decode.go:160 +0xfc
created by github.com/paulmach/osm/osmpbf.(*decoder).Start
        /Users/david/repos/osm/osmpbf/decode.go:152 +0x348
exit status 2
```

**Comment by dmholtz** [comment]
@paulmach Please find the [pbf-file](https://drive.google.com/drive/folders/1yzRduTsbfmOlj_UZy7a3GYEjYhciEcT9?usp=sharing) which causes the issue on my Google Drive.

It is basically a subset of the planet file from Geofabrik and contains only ways tagged with coastline as well as the nodes involved.

I hope this is helpful for you to reproduce the error. According to my supervisor, there is syntactically nothing wrong with the file.

**Comment by paulmach** [comment]
Thanks for the file, I noticed that oversight when I was working on the filter pr yesterday https://github.com/paulmach/osm/pull/30/files#diff-b6f55d8e2caec39b3655c559de9feae4fbfb156bcbd8c093ad7784f38b5862e5R372

I merged all that, tagged a new [v0.3.0](https://github.com/paulmach/osm/releases/tag/v0.3.0) 

This code works on your file now.  Thank you.

**Comment by dmholtz** [comment]
@paulmach Thank you very much, the latest release works perfectly.

**Pull request merged**
